Limits the number of scopes rows in the listing
BearStudio/start-repo pull request #61
Opened 2024-10-08 08:13 UTC by MaximeBro

- Fixes #22

2024-10-08 08:41 UTC, yoannfleurydev commented on src/app/issues/PageIssues.tsx
> +  console.log({ issues });
```suggestion
```

2024-10-08 12:11 UTC, HugoPerard requested changes
Can you add updated screenshot please

2024-10-08 12:11 UTC, HugoPerard commented on src/app/issues/PageIssues.tsx
> +                                    <Tag style={{ zIndex: 9999 }}>{`+${
I think it's not normal to do that 😅
And for you knowledge, on Chakra UI components you a zIndex props, instead on use style -> zIndex

2024-10-08 12:11 UTC, HugoPerard commented on src/app/issues/PageIssues.tsx
> +                                    }`}</Tag>
We don't need to convert as number (with "+" to put it back at string after (with literal template between `)

2024-10-08 12:11 UTC, HugoPerard commented on src/app/issues/PageIssues.tsx
> +                                                )[700]
Two things :

1. Here you calculate every time a new swatch from the same color, it's better to declare one time the `generateSwatch(scope.color ?? brandColor)` and then use the result each time we need a color tint
2. In this case, we should not defined manually color, bg, dark stuff... You can use colorScheme props instead

2024-10-08 12:11 UTC, HugoPerard commented on src/app/issues/PageIssues.tsx
> +                                  }`}</Tag>
Same remark than above

2024-10-08 12:11 UTC, HugoPerard commented on src/app/issues/PageIssues.tsx
> +                                              )[700],
Same remark than above

2024-10-08 12:11 UTC, HugoPerard commented on src/app/issues/PageIssues.tsx
> +                                  bg="gray.800"
Did you try in light mode ?

2024-10-09 09:19 UTC, HugoPerard commented
@MaximeBro On mobile, we want text to be align on the left, not centered. That will also fix the alignment of the items according to the title/description length

![image](https://github.com/user-attachments/assets/447be4ab-8bfe-48cd-b76b-f6060f1de917)

2024-10-19 15:12 UTC, yoannfleurydev requested changes
<img width="563" alt="image" src="https://github.com/user-attachments/assets/792a806b-32bd-4ec7-8132-147df24b1eb8">

please fix the annotation on that PR

2024-10-19 15:12 UTC, yoannfleurydev commented on src/app/issues/PageIssues.tsx
>  import { generateSwatch } from '@/utils/colors';
Remove this import as it is not used anymore in that file.

2024-10-20 01:40 UTC, yoannfleurydev approved these changes

2024-10-20 01:48 UTC, merged